name: Automated Testing

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '30 3 * * *'
    - cron: '30 13 * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Java version as you provided
          distribution: 'temurin'

      # Step 4: Install Maven 3.9.9
      - name: Install Maven 3.9.9
        run: |
          curl -o maven.zip https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip
          tar -xf maven.zip
          echo "Maven 3.9.9 installation completed"

      # Step 5: Verify Maven version
      - name: Verify Maven version
        run: mvn -v

      # Step 6: Install Chrome
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      # Step 7: Build and run tests
      - name: Build and run tests
        run: |
          mvn clean install -DskipTests
          mvn clean test -Dbrowser=chrome

      # Step 8: Archive test reports
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
