name: Automated Testing

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Runs at 9:00 AM IST (3:30 AM UTC) every day
    - cron: '30 3 * * *'
    # Runs at 7:00 PM IST (1:30 PM UTC) every day
    - cron: '30 13 * * *'

jobs:
  test:
    runs-on: windows-latest  # Use the latest Windows environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Adjust if your project requires a different Java version
          distribution: 'temurin'

      # Step 4: Install Chrome browser (required for Selenium tests)
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      # Step 5: Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn dependency:resolve

      # Step 6: Build the project
      - name: Build the project
        run: mvn clean install -DskipTests

      # Step 7: Run tests with Chrome browser
      - name: Run tests
        run: mvn test -Dbrowser=chrome

      # Step 8: Archive test reports for debugging
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

      # Step 9: Debug Maven dependency tree (optional for troubleshooting)
      - name: Debug Maven dependencies
        if: failure()  # Only run if the previous step fails
        run: mvn dependency:tree
